style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://{{ .repoOrg }}/{{ .repoName }}
options:
  commits:
     filters:
       Type:
         - add
         - fix
         - rmv
         - chg
  commit_groups:
     title_maps:
       add: Added
       fix: Fixed
       rmv: Removed
       chg: Changed
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
